### ISSUE TITLE
Get rid of message related to reading in a subset of variables

### ISSUE THREAD

**Issue by dtburk** [ipums/ipumsr#10]
From ipumsr created by [dtburk](https://github.com/dtburk): mnpopcenter/ipumsr#72  

We shouldn't see this message when we specify a subset of variables with the `vars` argument to `read_ipums_micro()`:

```
Note: Using an external vector in selections is ambiguous.
ℹ Use `all_of(vars_of_interest)` instead of `vars_of_interest` to silence this message.
ℹ See <https://tidyselect.r-lib.org/reference/faq-external-vector.html>.
```

I got this message with ipumsr version 0.4.5 and tidyselect version 1.1.0.

**Comment by dtburk** [comment]
We should consider closing this one.

First, a clarification: This only happens when you pass the name of a vector that contains the variable names you want. E.g. you get the message with:
```
var_subset <- c("YEAR", "SERIAL", "INCTOT")
cps <- read_ipums_micro(
    ipums_example("cps_00006.xml"),
    data_file = ipums_example("cps_00006.dat.gz"),
    vars = var_subset
)
```

But not with 

```
cps <- read_ipums_micro(
    ipums_example("cps_00006.xml"),
    data_file = ipums_example("cps_00006.dat.gz"),
    vars = c("YEAR", "SERIAL", "INCTOT")
)
```

Probably there is nothing to do here; the warning from tidyselect now tells users how to make this less ambiguous, and the annoyance of the warning is probably outweighed by the convenience of supporting tidyselect syntax.

**Comment by robe2037** [comment]
Agreed, closing now.
