### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [ipums/ipumsr#23]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by robe2037** [comment]
@dtburk Some or all of this can be folded in with IPUMS Terra decommissioning and the upcoming NHGIS release. Worth discussing whether we want to maintain support for IPUMS Terra rasters by updating with `terra` or if we want to deprecate this functionality. `rgdal` underlies `read_ipums_sp`, which may also be worth deprecating in favor of `sf` support alone.

**Comment by rsbivand** [comment]
@robe2037  rgdal was archived yesterday, so please do move to submit an updated version of ipumsr as soon as possible. See https://github.com/r-spatial/evolution https://r-spatial.github.io/evolution/ for details.

**Comment by robe2037** [comment]
@rsbivand thanks for the update—we will be submitting a new CRAN release shortly. 

Reopening this issue until CRAN release goes through.

**Comment by robe2037** [comment]
0.7.0 has been released to CRAN without these dependencies.

**Comment by rsbivand** [comment]
@robe2037 thanks for your cooperation!
