### ISSUE TITLE
ipumsr and tidyselect 1.2.1

### ISSUE THREAD

**Issue by lionel-** [ipums/ipumsr#71]
The next version of tidyselect that I'm about to release will cause CRAN failures for ipumsr because its tests are checking for exact matches of error messages generated in tidyselect and these have now changed. Since error message contents aren't part of the tidyselect API, could you please use testthat snapshots instead?

**Comment by robe2037** [comment]
Will do—thanks for the heads-up.

@dtburk I will probably go ahead and update to testthat 3e as part of this fix.
