### ISSUE TITLE
Table not available through ipumsr?

### ISSUE THREAD

**Issue by sarah-hf** [ipums/ipumsr#74]
Hi there, I am trying to submit an NHGIS data extract through ipumsr and I'm unable to locate a table that I know is available through the website. The table is B19001H and I need it for both 2005-2009 ACS and 2014-2018 ACS. If helpful, the titles are:

- For 2005-2009 ACS: Household Income in the Past 12 Months (in 2009 Inflation-Adjusted Dollars) (White Alone, Not Hispanic or Latino Householder. 
- For 2014-2018 ACS: Household Income in the Past 12 Months (in 2018 Inflation-Adjusted Dollars) (White Alone, Not Hispanic or Latino Householder. 

Is it possible to make this available through ipumsr, or should I manually download this extract? Thank you!

**Comment by robe2037** [comment]
I'm able to successfully submit an extract request for B19001H using the following extract definition:

``` r
library(ipumsr)

define_extract_nhgis(
  datasets = ds_spec("2005_2009_ACS5b", "B19001H", "state")
)
```

One possibility is that you're looking for the table in the wrong dataset—B19001H is found in dataset `2005_2009_ACS5b`, not `2005_2009_ACS5a`, where some of the most common ACS tables are found. (The same should hold for the 2014-2018 ACS.)

If you're unsure, you can always check which dataset a table comes from with `get_metadata_nhgis()`. For instance:

``` r
library(ipumsr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

dt_meta <- get_metadata_nhgis("data_tables") |> 
  filter(name == "B19001H", grepl("2005", dataset_name))

dt_meta$dataset_name
#> [1] "2005_2009_ACS5b"
```
<sup>Created on 2024-05-21 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

If you're still having trouble submitting a request for this table, please provide your extract definition and submission code along with the error message you receive and that may help me identify the problem.

**Comment by sarah-hf** [comment]
Thanks so much - you were correct, the issue was that I was looking in the wrong dataset. I appreciate the quick help!
